// Helper generate email sekolah otomatis dari nama lengkap — aman & editable
// Dipakai di: CreateUserModal (auto-suggest, user tetap bisa edit manual)

const DEFAULT_DOMAIN = 'sekolah.sch.id'

export function getSchoolEmailDomain(): string {
  const env = process.env.NEXT_PUBLIC_SCHOOL_EMAIL_DOMAIN?.trim()
  return env && env.includes('.') ? env : DEFAULT_DOMAIN
}

/**
 * Slugify nama → local-part email
 * - hapus gelar: ", S.Pd", ", M.Pd" dll (potong di koma pertama)
 * - normalize aksen (é→e), lowercase
 * - hanya huruf/angka, spasi/hyphen/underscore → titik
 * - dot berurutan → single dot, trim dot di ujung
 */
export function slugifyNamaToLocalPart(nama: string): string {
  if (!nama) return ''
  // potong gelar setelah koma
  const beforeComma = nama.split(',')[0] ?? nama
  // normalize aksen + lowercase
  const normalized = beforeComma
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
  // ganti separator jadi spasi, lalu filter karakter
  const cleaned = normalized
    .replace(/[^a-z0-9\s._-]/g, ' ') // buang simbol aneh → spasi
    .replace(/[\s_-]+/g, ' ') // hyphen/underscore → spasi
    .trim()
  if (!cleaned) return ''
  const parts = cleaned.split(' ').filter(Boolean)
  // join dengan titik, max 3 kata pertama biar tidak terlalu panjang (opsional tapi aman)
  // contoh: "Muhammad Budi Santoso Wijaya" → "muhammad.budi.santoso.wijaya"
  const local = parts.join('.')
  // rapikan dot ganda & trim
  return local.replace(/\.+/g, '.').replace(/^\.+|\.+$/g, '').slice(0, 64)
}

export function generateSchoolEmail(nama: string, domain?: string): string {
  const local = slugifyNamaToLocalPart(nama)
  if (!local) return ''
  const d = (domain ?? getSchoolEmailDomain()).trim().toLowerCase()
  return `${local}@${d}`
}

/**
 * Cek apakah email terlihat seperti hasil auto-generate (untuk tracking manual edit)
 * - domain harus sekolah
 * - local-part hanya huruf/angka/titik (tanpa karakter aneh)
 */
export function isAutoGeneratedEmail(email: string): boolean {
  if (!email) return false
  const domain = getSchoolEmailDomain().toLowerCase()
  const lower = email.toLowerCase()
  if (!lower.endsWith(`@${domain}`)) return false
  const local = lower.split('@')[0] ?? ''
  return /^[a-z0-9.]+$/.test(local)
}
